### ISSUE TITLE
Erro ao gerar pdf do resumo da sessão

### ISSUE THREAD

**Issue by andreagudo** [interlegis/sapl#1009]
Ocorreu na sessão http://sapl31agudo.interlegis.leg.br/sessao/278/resumo 
Não ocorre em todas.

ExpatError at /relatorios/278/sessao-plenaria
not well-formed (invalid token): line 84, column 216
Request Method:	GET
Request URL:	http://sapl31agudo.interlegis.leg.br/relatorios/278/sessao-plenaria
Django Version:	1.9.12
Exception Type:	ExpatError
Exception Value:	
not well-formed (invalid token): line 84, column 216
Exception Location:	/usr/lib/python3.4/xml/dom/expatbuilder.py in parseString, line 223
Python Executable:	/var/interlegis/.virtualenvs/sapl/bin/python3
Python Version:	3.4.3
Python Path:	
['/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/bin',
 '/var/interlegis/sapl',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages']
Server time:	Qua, 12 Abr 2017 08:27:56 -0300

**Comment by edwardoliveira** [comment]
Esse erro foi causado por um problema na máquina de produção (sapl31agudo). Vamos investigar o que pode ter ocorrido, mas enquanto isso vou registrando aqui as mensagens de erro.

```
Internal Server Error: /relatorios/278/sessao-plenaria
Traceback (most recent call last):
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/interlegis/sapl/sapl/relatorios/views.py", line 798, in relatorio_sessao_plenaria
    lst_oradores)
  File "/var/interlegis/sapl/sapl/relatorios/templates/pdf_sessao_plenaria_gerar.py", line 293, in principal
    tmp_pdf = parseString(tmp)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages/trml2pdf/trml2pdf.py", line 715, in parseString
    r = _rml_doc(data.strip())
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.4/site-packages/trml2pdf/trml2pdf.py", line 215, in __init__
    self.dom = xml.dom.minidom.parseString(data)
  File "/usr/lib/python3.4/xml/dom/minidom.py", line 1970, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.4/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.4/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 84, column 216

```

**Comment by edwardoliveira** [comment]
@andreagudo Verifique se solucionou, por favor. Caso contrário pode reabrir.

**Comment by andreagudo** [comment]
Resolvido.

**Comment by andreagudo** [comment]
Reabri porquê voltou a aparecer um erro com o travessão, no pdf da sessão, na ementa do PL 15/2017 (aparece &#8211;).
http://sapl31agudo.interlegis.leg.br/relatorios/648/sessao-plenaria

**Comment by edwardoliveira** [comment]
@andreagudo Por favor, veja se está solucionado.

**Comment by andreagudo** [comment]
Ainda não.
![captura de tela de 2017-09-01 13 37 17](https://user-images.githubusercontent.com/19169882/29979176-d713297c-8f1a-11e7-9355-b11b8e1a0662.png)

**Comment by edwardoliveira** [comment]
commit #71b0b59

@andreagudo Veja se solucionou, por favor.

**Comment by andreagudo** [comment]
Resolvida.
