### ISSUE TITLE
Erro ao subir a aplicação gunicorn/supervisor

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3266]
## Comportamento Esperado
Subir aplicação ao usar Gunicorn/Supervisor

## Comportamento Atual
Retorna o seguinte erro:

`Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>`

## Possível Solução

no commit  https://github.com/interlegis/sapl/commit/85be85f75e3d27cf226c1937596324a63d4a8aba#diff-02901114a107d9b7f627eda549ab990bL31-L34 foi retirado este código ocasionando o erro

Adicionar o seguinte código ao gunicorn_start.sh:

`cd $DJANGODIR
source /var/interlegis/.virtualenvs/sapl/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH`

## Seu Ambiente

* Versão usada (_Release_): 3.1.161-RC11

**Comment by edwardoliveira** [comment]
Poderia submeter um PR?

**Comment by puera** [comment]
@edwardoliveira sim, assim que tiver no PC eu envio esse PR
