### ISSUE TITLE
Falhas nos testes automáticos

### ISSUE THREAD

**Issue by edwardoliveira** [interlegis/sapl#33]
Consertar testes unitários e de integração que estão falhando devido as mudanças dos últimos 3 meses.

**Comment by edwardoliveira** [comment]
Executando o comando ``./manage.py test``, dá o seguinte erro na minha máquina:

```
Creating test database for alias 'default'...
E
======================================================================
ERROR: legacy.test_renames (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: legacy.test_renames
Traceback (most recent call last):
  File "/home/eribeiro/.virtualenvs/sapl/lib/python3.4/site-packages/django/apps/registry.py", line 148, in get_app_config
    return self.app_configs[app_label]
KeyError: 'legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/eribeiro/python-projects/sapl/legacy/test_renames.py", line 5, in <module>
    from .migration import appconfs, get_renames, legacy_app
  File "/home/eribeiro/python-projects/sapl/legacy/migration.py", line 28, in <module>
    legacy_app = apps.get_app_config('legacy')
  File "/home/eribeiro/.virtualenvs/sapl/lib/python3.4/site-packages/django/apps/registry.py", line 150, in get_app_config
    raise LookupError("No installed app with label '%s'." % app_label)
LookupError: No installed app with label 'legacy'.


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
Destroying test database for alias 'default'...

```

O que **EU** estou fazendo de errado? O código do commit parece OK, fora esta mensagem.

**Comment by marciomazza** [comment]
`./manage.py test` rodaria os testes da forma padrão do django, com `unittest`, que nós não usamos. Usamos o **py.test** que tem outra estratégia de descoberta de testes e uma ativação mais simples. Em geral rodamos os testes com `py.test`. Esse comando roda todos os testes do diretório corrente e seus subdiretórios.

Existe uma peculiaridade nos nossos testes: parte deles tem de rodar com outro `settings.py`. Para rodar tudo precisamos então de 2 comandos executados na raiz do projeto:
```
py.test
py.test --ds=crud_tests.settings crud_tests
```
Seria muito bom ter uma forma de rodar tudo com simplesmente `py.test`, mas não consegui descobrir ainda.

Para facilitar reuni os comandos necessários no script `test_and_check_qa.sh` na raiz.

TL;DR
Rode os testes com
```
./test_and_check_qa.sh
```

**Comment by edwardoliveira** [comment]
+1. Passou todos os testes. :+1:

**Comment by marciomazza** [comment]
Já fiz em f8daa48.
