### ISSUE TITLE
Menu "Audiencia Publica" parou de funcionar, mostra erro 500

### ISSUE THREAD

**Issue by alex-wsul** [interlegis/sapl#3438]
Nestes ultimos dias, a opção "Audiencia Publica" parou de abri, mostrando o erro: 

## Possível Solução

Tentei atualizar para o ultimo release 3.1.162-RC9, mas ai tudo parou, precisei restaurar backup, mas continua o problema da "audiencia publica" não abrir.
não entendi porque não deu certo atualizar, seguindo os passos de sempre.
 

## Passos para Reproduzir (para bugs)

1. acesse https://sapl.cmcc.rs.gov.br/audiencia/
2. mostra erro: Ocorreu um erro inesperado! Erro 500
3. tentei atualizar para o 3.1.162, ai parou tudo, erro de sintaxe em varios scripts
4. parece que django nao é compativel com o python atual do env que é 3.5.2

## Seu Ambiente

* Versão usada (_Release_): 3.1.160
* Nome e versão do navegador: Chrome
* Nome e versão do Sistema Operacional (desktop ou mobile): Desktop mac os

**Comment by AlGouvea** [comment]
Boa tarde,
Você poderia por favor simular o erro localmente e em seguida anexar o arquivo sapl.log?

**Comment by alex-wsul** [comment]
Boa tarde @AlGouvea,

trecho sapl.log com o erro:
/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/exception.py django.request:handle_uncaught_exception:135 Internal Server Error: /audiencia/
Traceback (most recent call last):
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/interlegis/sapl/sapl/crud/base.py", line 231, in dispatch
    request, *args, **kwargs)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.5/site-packages/django/views/generic/list.py", line 175, in get
    context = self.get_context_data()
  File "/var/interlegis/sapl/sapl/audiencia/views.py", line 41, in get_context_data
    url_materia = reverse('sapl.materia:materialegislativa_detail', kwargs={'pk': materia.id})
AttributeError: 'NoneType' object has no attribute 'id'
-----------------------------------

 Fiz uma gambiarra pra corrigir, olhei o codigo mais atual e vi que em alguns casos o url_materia era setado None, ai modifiquei:
 
 codigo original:
             for row in context['rows']:
                coluna_materia = row[3] # se mudar a ordem de listagem mudar aqui
                if coluna_materia[0]:
                    materia = audiencia_materia[row[0][0]]
                    url_materia = reverse('sapl.materia:materialegislativa_detail', 
                                          kwargs={'pk': materia.id})
                    row[3] = (coluna_materia[0], url_materia)
            return context

codigo alterado que funcionou:
            for row in context['rows']:
                coluna_materia = row[3] # se mudar a ordem de listagem mudar aqui
                if coluna_materia[0]:
                    materia = audiencia_materia[row[0][0]]
                    **url_materia = None** # reverse('sapl.materia:materialegislativa_detail', kwargs={'pk': materia.id})
                    row[3] = (coluna_materia[0], url_materia)
            return context



sei que é errado mas quebrou o galho...

to na versao 3.1.160 e nao consigo mais atualizar, só da erro... ai tenho que voltar pra esta versao

**Comment by edwardoliveira** [comment]
Vcs poderiam nos passar um dump da base de vcs? Sugiro abrir um ticket no OSTicket (https://https://suporte.interlegis.leg.br/) somente para que vcs possam enviar a base de vcs sem ser as claras via Github. 

Nesse ticket vcs podem anexar o dump do BD  ou, se for muito grande, então disponibilizar via OneDrive/Dropbox/etc e enviar o link pra gente via OSTicket para que possamos investigar o motivo deste erro.

**Comment by edwardoliveira** [comment]
Vou fechar essa issue pq ainda não obtivemos resposta.
