### ISSUE TITLE
Erro 500 ao tentar gerar etiqueta de matéria legislativa

### ISSUE THREAD

**Issue by puera** [interlegis/sapl#3483]
## Passos para Reproduzir (para bugs)

1. Pesquisar Matéria Legislativa 
2. Clicar no icone da etiqueta -  Exemplo: https://sapl.armacaodosbuzios.rj.leg.br/relatorios/1817/etiqueta-materia-legislativa

## Traceback
`Traceback (most recent call last):
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/interlegis/sapl/sapl/relatorios/views.py", line 1659, in etiqueta_materia_legislativa
    pdf_file = gera_etiqueta_ml(materia_legislativa, base_url)
  File "/var/interlegis/sapl/sapl/relatorios/views.py", line 1624, in gera_etiqueta_ml
    base64_data = create_barcode(ml_info, 100, 500)
  File "/var/interlegis/sapl/sapl/utils.py", line 406, in create_barcode
    data = b64encode(barcode.asString('png'))
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/reportlab/graphics/shapes.py", line 854, in asString
    return renderPM.drawToString(self, fmt=format,showBoundary=getattr(self,'showBorder',
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 685, in drawToString
    drawToFile(d,s,fmt=fmt, dpi=dpi, bg=bg, configPIL=configPIL)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 681, in drawToFile
    c.saveToFile(fn,fmt)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 313, in saveToFile
    im = self.toPIL()
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 309, in toPIL
    getattr(im,'frombytes',getattr(im,'fromstring'))(self._gs.pixBuf)
  File "/var/interlegis/.virtualenvs/sapl/lib/python3.8/site-packages/PIL/Image.py", line 546, in __getattr__
    raise AttributeError(name)
AttributeError: fromstring`

## Seu Ambiente

* Versão usada (_Release_): 3.1.162-RC13

**Comment by edwardoliveira** [comment]
Vc está rodando em container Docker?

**Comment by puera** [comment]
@edwardoliveira não, está sendo rodado na estrutura comum, eu fiz até um teste com SAPL zerado com todas as dependências instaladas e o erro acontece

**Comment by edwardoliveira** [comment]
Provavelmente vc tá problema em versão de lib, mais especificamente o Pillow foi atualizado pra uma versão mais recente na qual eles removeram um método que o gerador de relatório usa. Procura no Google pela mensagem de erro e o que eles recomendam fazer nesse caso. No Docker essas versões são fixas, não temos esse problema.

A versão que usamos é Pillow==8.3.2

**Comment by puera** [comment]
@edwardoliveira dei um pip freeze aqui e consta essa versão nas minhas dependências também Pillow==8.3.2

**Comment by edwardoliveira** [comment]
Não raro, as bibliotecas Python são "camadas" (wrappers) em cima de libs C/C++ do SO. Pode ser o caso aqui. Eu sugiro pesquisar esse erro no Google e, quando possível usar uma instalação baseada em container. Evita esse tipo de variação de instalação. Antes de migrarmos pra container até mesmo atualizações automáticas do SO quebravam as aplicações Python as vezes.

**Comment by edwardoliveira** [comment]
Fechando essa issue pq não tivemos resposta.
